# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-10 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('street', '0005_recent_upcoming'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allow_notification',
            field=models.IntegerField(default=1, help_text='1-ON,2-OFF'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rate_app',
            field=models.IntegerField(default=1, help_text='rate is from 1-5'),
        ),
    ]
