# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-10 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('street', '0009_usermedia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermedia',
            old_name='video_url',
            new_name='video_link',
        ),
    ]
