# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-10 05:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('street', '0010_auto_20180110_0524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recent',
        ),
    ]
