# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-10 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('street', '0012_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name_plural': 'Notification'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='userprofilepics/sank.png', upload_to='userprofilepics'),
        ),
    ]
