# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-11 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('street', '0013_auto_20180110_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayerrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='street.Userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='userprofilepics/sank.png', upload_to='userprofilepics'),
        ),
    ]
