# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-13 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('street', '0017_auto_20180111_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='street.Userprofile'),
        ),
    ]
