# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-15 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('street', '0018_auto_20180113_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermedia',
            name='audio',
            field=models.FileField(blank=True, upload_to='upload_to_audio'),
        ),
        migrations.AlterField(
            model_name='usermedia',
            name='video_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploadto_video_image'),
        ),
        migrations.AlterField(
            model_name='usermedia',
            name='video_link',
            field=models.URLField(blank=True),
        ),
    ]
