codes_msg = {
    1000: "Mandatory fields are missing",
    1001: "Enter valid Data",
    1002: "Unable to Save and Update",
    1004: "Unable to Delete",
    1005: "Enter Valid Note",
    1006: "Already in Drafts",
    1007: "Unable to Delete Question (Question Paper Already Generated)",
    1008: 'Invalid Prayer Request',
    1009: 'User Does Not Exist',
    1010: 'Invalid bookmark',
    1011: 'Email/Phone Does Exists',
    1012: 'Invalid Notification Status',
    1013: 'Email/Phone Already Exists',
    1014: 'You Already Liked This Prayer',
    1015: 'Prayer Request Updated Succesfully',
    1016: 'Invalid Prayer Request',
    1017: 'Unable to access Userprofile',
    1018: 'You are not Admin',
    1019: 'You cant like your own Post',
    1020: 'Succesfully Uploaded Media',
    1021: 'You are not admin to upload this Media',




    1022: 'Bookmark Added Succesfully',
    1023: 'Unable to save reviews',
    1024: 'Empty Review',
    1025: 'Unable to Save Bookamark',
    1026: 'No Sample to show',
    1027: 'Issue is raised successfully, thank you.',
    1028: 'Answer added succesfully',
    1029: 'Unable to add solution',
    1030: 'Answer update succesfully',
    1031: 'Invalid solution',
    1032: 'Unable to edit the solution',
    1033: 'Already you added a answer',
    1034: 'Succesfully deleted solution',
    1035: 'Unable to delete solution',
    1036: 'Succesfully updated notification status',
    1037: 'Unable to update the notification status',
    1038: 'Invalid notification status',
    1039: 'Invalid visibality',
    1040: 'Not allowed to delete other\'s solution',
    1041: 'Not allowed to edit other\'s solution',



    9000: "Prayer Request Added",
    9001: "Prayer Request Deleted Succesfully",
    9002: "Userprofile Updated succesfully",
    9003: "Succesfully Liked",
    9004: "Updated Successfully",
    9005: "note_list information",
    9006: "Note added successfully",
    9007: "Deleted Successfully",
    9008: "Search is Successfull",
    9009: "Note Detail Information",
    9010: "Already in Drafts",
    9019: "Class name List",
    9020: "Successfully Updated",
    9021: "List Of Question Paper",
    9022: "Deleted Successfully And Saved In Drafts",
    9023: "Invalid subject",
    9024: "Unable to Create",
    9025: "Invalid Class",
    9026: "Enter Valid Data For Location",
    9027: "Invalid Note",
    9028: "Question is Created And Saved ",
    9029: "Not Valid Question",
    9030: 'Saved successfully',
    9031: 'attempts over',
    9032: 'Solution Rating Added Successfully',
    9033: 'Solution Cannot Rate By Yourself',
    9034: 'Invalid Solution',
    9035: 'Enter valid data ',
    9036: 'Enter valid Report type',
    9037: 'Solution Cannot Report By Yourself',
    9038: 'You Already Reported',
    
    

    2000: 'Invalid user',
    2001: 'Invalid question paper',
    2002: 'Invalid lesson',
    2003: 'Invalid Question Paper',
    2004: 'Question Created Successfully',
    2005: 'Question Updated Successfully',
    2006: 'Invalid Question',
    2007: 'Invalid Master Question',
    2008: 'Question Added Successfully',
    2009: 'Invalid subject',
    2010: 'Question Paper Saved Successfully',
    2011: 'Unable to access user profile',
    2012: 'User Registered Successfully, but unable to generate token',
    2013: 'User Registered & pending for otp verification',
    2014: 'Already this mobile number is exist!',
    2015: 'OTP verified, registration completed successfully',
    2016: 'OTP verified, but unable to generate token',
    2017: 'OTP not matching, please try again',
    2018: 'Mobile number or password may be wrong',
    2019: 'Mobile number is not verified, please verify the mobile number.',
    2020: 'Login success, but unable to generate token, please try again',
    2021: 'Logged out successfully',
    2022: 'Unable to logged out, please try again',
    2023: 'Authentication failed, please login to access this page',
    2024: 'Mobile number is not registered',
    2025: 'OTP sent to your registered mobile, please check & enter the OTP',
    2026: 'Password updated successfully',
    2027: 'Old password is not matching, please try again',
    2028: 'Mobile number changed successfully',
    2029: 'Test result summary saved successfully',
    2030: 'Unable to save please try again',
    2031: 'Invalid class',
    2032: 'Unable to create user, please try again',
    2033: 'Unable to create user profile',
    2034: 'OTP sent to your old mobile number, please check & enter the OTP',
    2035: 'OTP verified, new mobile number updated successfully',
    2036: 'OTP verified, but unable to update new mobile number, please try again',
    2037: 'Mark updated successfully',
    2038: 'Invalid question',
    2039: 'OTP verified successfully',
    2040: 'Total score should be equal or greater than score',
    2041: 'PDF generated successfully',
    2042: 'There is no data to generate PDF',
    2043: 'Invalid phone number',
    2044: 'Validation failed',
    2045: 'Unable to save user profile',
    2046: 'Unable to create token, please try again',
    2047: 'Already this email is exist!',
    2048: 'New password should not be same as old password',
    2049: 'Invalid otp type',
    2050: 'Not allowed to save test result! your attempts are over',
    2051: 'Already you added this question',
    2052: 'Question paper title is not changed! please add new name',
    2053: 'Invalid Leaderboard type',
    2054: 'Unable to save points',

    3000: 'OK',
    3001: 'Oops something went wrong! please try again',
    3002: 'This field is required.',
    3003: 'Invalid role',
    3004: 'Incorrect password',
}
